1-run_inline

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,11 @@
 #!/bin/bash
 
+#check if PYCODE evn variable is set
+if [ -z "$PYCODE" ]; then
+	echo "Error: Environment variable of PYCODE is not set."
+	exit 1
+fi
+
+#Run python code stored in PYCODE
+
+python3 -c "$PYCODE"
